import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "./Providers";
import Header from "components/Header";
import Footer from "components/Footer";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Box as="main" minH="100vh" position="relative" zIndex={1}>
            {children}
          </Box>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
