import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

import { Providers } from "./Providers";
import Header from "components/Header";
import Footer from "components/Footer";
const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={workSans.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
